### PR TITLE
Fonts, diagrams, partner logos, and graphics for the new la…

### PR DESCRIPTION
**Pull request by mikepsinn**
…nding page

### CODE REVIEW

**Comment by vincenzodomina** [comment]
Please remove the architectural diagrams from this pull request, and we can add the final ones in another.

**Comment by mikepsinn** [comment]
OK.  What are the final ones?  Why wouldn't we want different versions for different use cases? 

It's kind of frustrating to spend a lot of time on things and the only feedback on the pull request is to delete them.

**Review by vincenzodomina — CHANGES_REQUESTED** [review]
I would also remove the purple "logo" from the template which is not ours

**Comment by mikepsinn** [comment]
Task linked: [CU-2hhfnt7 Fix radius on images](https://app.clickup.com/t/2hhfnt7)

**Comment by mikepsinn** [comment]
Task linked: [CU-23efcme "Blocks" with different boarder radius](https://app.clickup.com/t/23efcme)

**Pull request merged**
